import { Montserrat, Outfit } from "next/font/google";
import "./globals.css";
import { ClerkProvider, SignedOut, SignedIn, SignInButton, UserButton } from '@clerk/nextjs'

const inter = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
